# Production Environment Configuration for TmuxBot

# Production-specific provider overrides
providers:
  openai:
    # Production-optimized parameters
    default_parameters:
      temperature: 0.7  # Standard temperature for production
      max_tokens: 4096  # Full token limit for production

  openrouter:
    # Use high-quality models in production
    model_mappings:
      "gpt-4o": "openai/gpt-4o"  # Use full GPT-4o in production
      "claude-3.5-sonnet": "anthropic/claude-3.5-sonnet"  # Use full Claude Sonnet

# Production-specific agent configurations
agents:
  primary:
    cost_optimization: false  # Disable cost optimization in production
    providers:
      - name: "openai"
        weight: 1.2  # Prefer OpenAI in production for reliability
        max_cost_per_1k_tokens: 0.03
      - name: "openrouter"
        weight: 1.0
        max_cost_per_1k_tokens: 0.02

  coder:
    # Use high-quality models for production coding tasks
    providers:
      - name: "openai"
        weight: 1.1
        max_cost_per_1k_tokens: 0.03
      - name: "openrouter"
        weight: 1.0
        max_cost_per_1k_tokens: 0.025

  devops:
    cost_optimization: false  # Full reliability for DevOps
    providers:
      - name: "openai"
        weight: 1.1
        max_cost_per_1k_tokens: 0.03
      - name: "openrouter"
        weight: 0.9
        max_cost_per_1k_tokens: 0.02

  sysadmin:
    cost_optimization: false  # Full reliability for SysAdmin
    providers:
      - name: "openai"
        weight: 1.2  # Prioritize reliability for system administration
        max_cost_per_1k_tokens: 0.03
      - name: "openrouter"
        weight: 0.8
        max_cost_per_1k_tokens: 0.02

# Production cost limits (higher than development)
cost_limits:
  daily_limit_usd: 100.0  # Higher daily limit for production
  per_request_limit_usd: 2.0  # Higher per-request limit
  warning_threshold_usd: 80.0

# Production performance settings
performance:
  timeout_seconds: 45  # Slightly longer timeout for production reliability
  max_retries: 5  # More retries for production stability
  circuit_breaker_enabled: true  # Enable circuit breaker in production

# Production logging (less verbose)
logging:
  level: "INFO"
  log_requests: false  # Disable request logging for performance
  log_responses: false  # Disable response logging for security
  log_costs: true  # Always log costs in production
  log_performance_metrics: true

# Production monitoring and alerting
monitoring:
  enable_cost_alerts: true
  enable_performance_alerts: true
  enable_error_alerts: true
  alert_thresholds:
    cost_warning_usd: 80.0
    cost_critical_usd: 95.0
    response_time_warning_ms: 30000
    error_rate_warning_percent: 5.0

# Production-specific context rules
context_rules:
  # In production, prioritize reliability over cost
  code_generation:
    - openai  # Use OpenAI first for reliability
    - openrouter

  text_analysis:
    - openai
    - openrouter

  system_administration:
    - openai  # Prioritize reliability for system tasks
    - openrouter

  general:
    - openai
    - openrouter

# Production feature flags
features:
  enable_cost_optimization: false  # Disable in production for reliability
  enable_performance_monitoring: true
  enable_adaptive_routing: true  # Enable adaptive routing in production
  enable_circuit_breaker: true
  enable_request_caching: true  # Enable caching for performance
  enable_metrics_collection: true

# Production tool integrations
integrations:
  # Enable production monitoring tools
  enable_prometheus_metrics: true
  enable_health_checks: true
  enable_admin_interface: false  # Disable admin interface in production

  # External monitoring integrations
  datadog_enabled: false
  new_relic_enabled: false
  sentry_enabled: true

# Production security settings
security:
  # Strict security for production
  require_api_key_validation: true
  enable_rate_limiting: true
  log_sensitive_data: false  # Never log sensitive data in production
  enforce_https: true
  api_key_rotation_days: 90

# Production deployment settings
deployment:
  health_check_path: "/health"
  readiness_check_path: "/ready"
  metrics_path: "/metrics"

  graceful_shutdown_timeout: 30
  startup_probe_delay: 10
  liveness_probe_interval: 30

# Production backup and recovery
backup:
  enable_config_backup: true
  enable_conversation_backup: false  # Disable for privacy
  backup_retention_days: 30

# Production resource limits
resources:
  max_concurrent_requests: 50
  max_memory_mb: 1024
  max_cpu_cores: 2.0